package cli

import (
	"errors"
	"fmt"
	"os"

	"github.com/nebucloud/ssf/pkg/artifact"
	"github.com/spf13/cobra"
)

func newInitCommand() *cobra.Command {
	var (
		artifactType string
		outputPath   string
		force        bool
	)

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Generate a starter ssf.yaml in the current directory",
		Long: `Generate a starter ssf.yaml tailored to a given artifact type.

With --type, the generated file includes type-appropriate defaults (e.g., a
binary path for binary, a registry reference for oci). Without --type, ssf
defaults to binary since it's the simplest type to wire (no registry / no
credentials).

Refuses to overwrite an existing ssf.yaml unless --force is set.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInit(artifactType, outputPath, force)
		},
	}
	cmd.Flags().StringVar(&artifactType, "type", "binary", "artifact type (oci | binary | crate | npm | derivation | blob)")
	cmd.Flags().StringVarP(&outputPath, "output", "o", "ssf.yaml", "output path")
	cmd.Flags().BoolVarP(&force, "force", "f", false, "overwrite an existing file")
	return cmd
}

func runInit(artifactTypeRaw, outputPath string, force bool) error {
	t := artifact.Type(artifactTypeRaw)
	if !t.IsValid() {
		return fmt.Errorf("--type %q is not recognized (one of %v)", artifactTypeRaw, artifact.AllTypes)
	}

	if !force {
		if _, err := os.Stat(outputPath); err == nil {
			return fmt.Errorf("%s already exists (re-run with --force to overwrite)", outputPath)
		} else if !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("stat %s: %w", outputPath, err)
		}
	}

	tmpl := starterTemplate(t)
	if err := os.WriteFile(outputPath, []byte(tmpl), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}

	fmt.Printf("wrote %s\n", outputPath)
	fmt.Printf("  type:   %s\n", t)
	fmt.Printf("  next:   ssf run --dry-run %s\n", outputPath)
	return nil
}

// starterTemplate returns the ssf.yaml content for a given artifact type.
// The templates intentionally include comments pointing at the canonical spec
// so users see where to look up the rest of the schema rather than discovering
// it via trial-and-error.
func starterTemplate(t artifact.Type) string {
	header := `# Generated by ssf init — see SSF-SPEC-ssf-yaml for the full schema reference
# https://github.com/nebucloud/docs/blob/main/SSF-SPEC-ssf-yaml.md

version: "1"

`
	switch t {
	case artifact.TypeBinary:
		return header + `artifact:
  type: binary
  reference: "./your-binary"

signing:
  key: file://cosign.key

pipeline:
  - step: sbom
    format: spdx
    output: sbom.spdx.json

  - step: sign

  - step: verify

  - step: attest
    predicates:
      - type: sbom
        source: sbom.spdx.json

policy:
  fail_open: false

output:
  report: ssf-report.json
  format: json
`

	case artifact.TypeOCI:
		return header + `artifact:
  type: oci
  reference: "ghcr.io/your-org/your-image:${VERSION}"

signing:
  key: file://cosign.key

pipeline:
  - step: sbom
    format: spdx
    output: sbom.spdx.json

  - step: sign

  - step: attest
    predicates:
      - type: slsa-provenance
      - type: sbom
        source: sbom.spdx.json

  - step: log

policy:
  fail_open: false
`

	case artifact.TypeCrate:
		return header + `artifact:
  type: crate
  reference: "your-crate@${VERSION}"

signing:
  key: file://cosign.key

pipeline:
  - step: sbom
    format: spdx
    output: sbom.spdx.json

  - step: sign

  - step: attest
    predicates:
      - type: slsa-provenance
`

	case artifact.TypeNPM:
		return header + `artifact:
  type: npm
  reference: "@your-scope/your-package@${VERSION}"

signing:
  key: file://cosign.key

pipeline:
  - step: sbom
    format: cyclonedx
    output: sbom.cyclonedx.json

  - step: sign

  - step: attest
    predicates:
      - type: sbom
        source: sbom.cyclonedx.json
`

	default:
		// Fall back to the binary template for derivation/blob since
		// they share the local-file flow. Type-specific templates land
		// alongside their dispatch.
		return header + fmt.Sprintf(`artifact:
  type: %s
  reference: "./your-artifact"

signing:
  key: file://cosign.key

pipeline:
  - step: sign
`, t)
	}
}
